### ISSUE TITLE
Feinstaub-meter not working

### ISSUE THREAD

**Issue by peterpoetzi** [PPOE/feinstaub-meter#8]
It looks like this url: https://kamerascheu.at/feinstaub-meter/index.php results in 404 error and has an invalid SSL certificate (issued by let's encrypt authority **x3**, but certificate chain links let's encrypt authority **x1**)

**Comment by PeterTheOne** [comment]
Thanks for the notice!

**Comment by PeterTheOne** [comment]
fixed
